x-brightsky:
  &brightsky
  build: .
  depends_on:
    - postgres
    - redis
  environment:
    BRIGHTSKY_DATABASE_URL: postgres://postgres:pgpass@postgres
    BRIGHTSKY_REDIS_URL: redis://redis

services:
  postgres:
    image: postgres:16-alpine
    shm_size: 512mb
    environment:
      POSTGRES_PASSWORD: pgpass
    volumes:
      - .data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:5-alpine
    restart: unless-stopped
  worker:
    <<: *brightsky
    command: --migrate work
    restart: unless-stopped
  web:
    <<: *brightsky
    command: serve --bind 0.0.0.0:5000
    restart: unless-stopped
    ports:
      - 5000:5000
  brightsky:
    <<: *brightsky
    scale: 0
